// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdKcZSQGD5XG_nu_csSGCnuW6B8Ctw5H0',
    appId: '1:506294411130:web:1594e261d184819df9c0c3',
    messagingSenderId: '506294411130',
    projectId: 'messhub-52df7',
    authDomain: 'messhub-52df7.firebaseapp.com',
    storageBucket: 'messhub-52df7.appspot.com',
    measurementId: 'G-NSY83C8C1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBONkYpeCZTvhYuJ0KuzhdETgXN3CeQDiE',
    appId: '1:506294411130:android:c267ba8e0a41e8d0f9c0c3',
    messagingSenderId: '506294411130',
    projectId: 'messhub-52df7',
    storageBucket: 'messhub-52df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCWj_FLdpwb5tp4g9TJ9Wg_tOZ5gccFg',
    appId: '1:506294411130:ios:1f5856c19c12a0d3f9c0c3',
    messagingSenderId: '506294411130',
    projectId: 'messhub-52df7',
    storageBucket: 'messhub-52df7.appspot.com',
    iosBundleId: 'com.example.messhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVCWj_FLdpwb5tp4g9TJ9Wg_tOZ5gccFg',
    appId: '1:506294411130:ios:1f5856c19c12a0d3f9c0c3',
    messagingSenderId: '506294411130',
    projectId: 'messhub-52df7',
    storageBucket: 'messhub-52df7.appspot.com',
    iosBundleId: 'com.example.messhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdKcZSQGD5XG_nu_csSGCnuW6B8Ctw5H0',
    appId: '1:506294411130:web:031452c08475c43bf9c0c3',
    messagingSenderId: '506294411130',
    projectId: 'messhub-52df7',
    authDomain: 'messhub-52df7.firebaseapp.com',
    storageBucket: 'messhub-52df7.appspot.com',
    measurementId: 'G-1GL3HJ04ZZ',
  );

}